set(CPACK_PACKAGE_VERSION ${PACKAGE_VERSION})
set(CPACK_GENERATOR "RPM;DEB;TGZ")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
if (PACKAGE_RELEASE)
    set(CPACK_PACKAGE_RELEASE ${PACKAGE_RELEASE})
else()
    set(CPACK_PACKAGE_RELEASE "1")
endif()

set(CPACK_PACKAGE_CONTACT "The overlaybd authors")
set(CPACK_PACKAGE_VENDOR "Overlaybd")
set(CPACK_PACKAGING_INSTALL_PREFIX "/")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}")

set(CPACK_RPM_PACKAGE_LICENSE "Apache v2.0")
set(CPACK_RPM_PACKAGE_RELEASE ${PACKAGE_RELEASE})
set(CPACK_RPM_PACKAGE_SUMMARY "Overlaybd backtore for tcmu")
set(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_RPM_PACKAGE_SUMMARY})

set(CPACK_DEBIAN_PACKAGE_VERSION "${PACKAGE_VERSION}-${PACKAGE_RELEASE}")


set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

include(CPack)

# Custom targets for easy package building
add_custom_target(deb
    COMMAND ${CMAKE_CPACK_COMMAND} --verbose -G DEB
    DEPENDS ${PROJECT_NAME}
    COMMENT "Building DEB package"
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)

add_custom_target(rpm
    COMMAND ${CMAKE_CPACK_COMMAND} --verbose -G RPM
    DEPENDS ${PROJECT_NAME}
    COMMENT "Building RPM package"
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)

add_custom_target(packages
    COMMAND ${CMAKE_CPACK_COMMAND} --verbose
    DEPENDS ${PROJECT_NAME}
    COMMENT "Building all packages (DEB and RPM)"
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)

add_custom_target(tgz
    COMMAND ${CMAKE_CPACK_COMMAND} --verbose -G TGZ
    DEPENDS ${PROJECT_NAME}
    COMMENT "Building TGZ package"
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)
